# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-04-12 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('description', models.TextField(max_length=5000)),
                ('injured', models.IntegerField(default=0)),
                ('killed', models.IntegerField(default=0)),
                ('num_vehicles', models.IntegerField(default=2)),
                ('num_persons', models.IntegerField(default=2)),
                ('malfunction', models.BooleanField(default=False)),
                ('alcohol', models.BooleanField(default=False)),
                ('pedestrians', models.IntegerField(default=0)),
                ('violation_code', models.CharField(blank=True, max_length=10, null=True)),
                ('w_seat_belts', models.IntegerField(default=2)),
                ('w_o_seat_belts', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['date', 'time'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
